### ISSUE TITLE
How many iterations can the NMT example go through a day with GPU?

### ISSUE THREAD

**Issue by tnq177** [mila-udem/blocks-examples#100]
I know this question has been asked before. And it's estimated to be ~70-75k iterations/day for the NMT example. In fact, I previously trained with English to French using data from here http://www-lium.univ-lemans.fr/~schwenk/cslm_joint_paper/. As I know, this is the data used in Bahdanau's paper. For this training, I got ~75k updates a day with the default configuration.

Recently, I trained on a smaller dataset (~60k sentences, ~1.4M words) with batch size of 40, but the best I can get is only ~40k iterations a day with a Nvidia Titan X 12GB. 

Does anybody have any idea why? Thanks!

**Comment by tnq177** [comment]
I noticed that previously I used ````hdf5/1.8.16-intel```. For later experiments, I used ```hdf5/1.8.8-intel```. Could this be the source of the problem? What is the best hdf5 version for the machine-translation example please? 

Also, sorry for this newbie problem, is there any difference between using ```CUDA/7.0``` and ```CUDA/7.5``` please? 

Thanks!

**Comment by nouiz** [comment]
I can't speed between NMT example, but for CUDA/7.5 is a more recent
version. If it is not yet installed, I would recommand to install 7.5

**Comment by tnq177** [comment]
Thanks @nouiz . Actually I have been training two models separately, one with CUDA/7.0 and another with CUDA/7.5. The one with 7.5 still has this speed issue. Wonder if anyone else have any idea please?

**Comment by nouiz** [comment]
I already saw some speed regression when changing the CUDA version. Can you
make sure that on the same hardware, with no other job running on the node,
you time with cuda 7.0 and with cuda 7.5. Be sure to delete theano cache
before each test. If they have different speed, then this would be a slow
down from the cuda version.

But this is not something frequently. If the GPU are in different computer,
it could be that one heat more then the other, so it get slowdown or the
cooler one get boosted but not the other.

Fred

**Comment by tnq177** [comment]
@nouiz I'm not entirely sure but I work on remote server machine. At all my jobs are running on nodes put in the same server I guess. The heat stuff could be the problem?

**Comment by nouiz** [comment]
Yes. Current GPU will auto boost if enough electricity and it is not too
hot. So if your server have multiple GPU, having just 1 GPU running or
multiple GPU running can change the speed of jobs.

**Comment by tnq177** [comment]
@nouiz  thanks a lot for your information. I'll close this issue for now.
