### ISSUE TITLE
Fix target embedding?

### ISSUE THREAD

**Issue by tnq177** [mila-udem/blocks-examples#101]
Hi, I want continue training on a trained model with the target embedding fixed. I drop this parameter ```/decoder/sequencegenerator/readout/lookupfeedbackwmt15/lookuptable.W``` from the parameters passed to ```GradientDescent```. I wonder if this is correct please? Thanks!

**Comment by rizar** [comment]
It is correct, assuming that you means the embeddings if output words that are fed back to the network.
