### ISSUE TITLE
Machine Translation : Deep Fusion

### ISSUE THREAD

**Issue by kadir-gunel** [mila-udem/blocks-examples#105]
Does MT code include _Deep Fusion method_ from "On Using Multilingual Corpora in NMT" [Gulcehre, 2015] ?
I ran the code but could not find any LM data inside search_model_X folder.
Am I missing it?

**Comment by orhanf** [comment]
Unfortunately, we don't have any implementation for _deep fusion_ in blocks (to my knowledge). 

But if you are interested, you can check [this](https://github.com/orhanf/GroundHog/tree/deep_fusion) repo, which is in GroundHog and no longer maintained.

**Comment by kadir-gunel** [comment]
Ok. Thank you.
