### ISSUE TITLE
Lenet : ValueError: '('train',)' split is not provided by this dataset. Available splits are (u'test', u'train').

### ISSUE THREAD

**Issue by jrabary** [mila-udem/blocks-examples#15]
It seems that the lenet example doesn't work with the current fuel api. I make it works by changing

`MNIST(("train",))` into `MNIST("train")`

**Comment by rizar** [comment]
Please update your Fuel installation, it is a recent change in the interface.

**Comment by nouiz** [comment]
If blocks could detect that easily and raise a good error, it would be
great. Not sure how easy it is.

**Comment by rizar** [comment]
Not sure how it can be checked when the version numbers are the same.

**Comment by nouiz** [comment]
Could you do some small test on the fuel object? Like build a dummy object
and check if he have new method/attribute?

**Comment by rizar** [comment]
For every particular change such a check indeed can be done. But interface keeps changing in Fuel and Blocks and it would be not too convenient to have such a check for every PR.

However, I hope we will make relatively frequent releases for those people who want to enjoy interface stability.

**Comment by nouiz** [comment]
Ok, but just to note, this is not just for user, but also to save
developers time by having less questions.

**Comment by rizar** [comment]
Sure, but seems like this is one of really fundamental issues of a fast workflow... so just like in `theano-users` all interactions with users will start with "please make sure that you are using the latest version".
