### ISSUE TITLE
bokeh=True does nothing in the mnist demo

### ISSUE THREAD

**Issue by rizar** [mila-udem/blocks-examples#18]
Should it be deleted or should be support live plotting in this demo?

**Comment by vikkamath** [comment]
Commit f311058 seems to have removed support for plotting. So I'm guessing it's to be removed.

**Comment by vikkamath** [comment]
Travis build failed because the blocks.extras module could not be found

**Comment by rizar** [comment]
We should add blocks-extras installation to travis.yml, just like Fuel 
is currently installed.
