### ISSUE TITLE
Requires bleeding-edge theano

### ISSUE THREAD

**Issue by pyrytakala** [mila-udem/blocks-examples#31]
Running the example in the README does not work with theano 0.7 but requires a bleeding-edge (requires at least PersistentCudaNdarrayID from misc/pkl_utils.py ). Could be good to mention this or make the main example compatible with 0.7.

**Comment by dwf** [comment]
Blocks unfortunately requires bleeding edge Theano itself, so making blocks-examples work with 0.7.0 is not tenable.
