### ISSUE TITLE
Simple Rnn's (LM RNN)

### ISSUE THREAD

**Issue by moore269** [mila-udem/blocks-examples#41]
Can anyone make an example of how to do a simple RNN? One with Back propagation through time would be sufficient.  Basically, ones similar to the one in this paper (LM RNN). 

http://www.fit.vutbr.cz/research/groups/speech/publi/2010/mikolov_interspeech2010_IS100722.pdf

**Comment by rizar** [comment]
The simplest RNN example we have is `parity_problem`. https://github.com/mila-udem/blocks-examples/tree/master/parity_problem. Also, we have a Markov chain modelling demo https://github.com/mila-udem/blocks-examples/tree/master/markov_chain, which is more like language modelling, but uses more advanced Blocks components.
