### ISSUE TITLE
Block examples run fail

### ISSUE THREAD

**Issue by longdt219** [mila-udem/blocks-examples#51]
When I run block examples, I have the error 
<b> /usr/bin/python: No module named cffi </b>
I did install cffi successfully 
<b> pip install cffi </b>

**Comment by dwf** [comment]
... Which example?

**Comment by dwf** [comment]
```
dwf@skyquake:~/src$ for project in fuel blocks blocks-examples; do cd $project && git checkout master && git pull && cd ..; done; grep -ri cffi blocks/* blocks-examples/* fuel/* |wc -l
Already on 'master'
Your branch is up-to-date with 'upstream/master'.
Already up-to-date.
Already on 'master'
Your branch is up-to-date with 'upstream/master'.
Already up-to-date.
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
       0
```

There's no reference to `cffi` in any of our projects, so I don't know what could be causing this, and it's impossible to tell without a stack trace. Suffice it to say it does not seem to be a problem that relates to this repository, so I'm closing the ticket. If you come to the conclusion that it is in fact somehow this repo causing the problem, please reopen the ticket and post a full stack trace.

**Comment by longdt219** [comment]
Thanks @dwf  for the quick reply, 
I run machine translation example and here is stack trace 

python -m machine_translation 

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/lt/work2/lduong/SpeechAlignment/code/block/blocks-examples/machine_translation/__main__.py", line 22, in <module>
    from machine_translation.stream import get_tr_stream, get_dev_stream
  File "machine_translation/stream.py", line 3, in <module>
    from fuel.datasets import TextFile
  File "/home/lduong/.local/lib/python2.7/site-packages/fuel/datasets/__init__.py", line 2, in <module>
    from fuel.datasets.base import (Dataset, IterableDataset,
  File "/home/lduong/.local/lib/python2.7/site-packages/fuel/datasets/base.py", line 9, in <module>
    from fuel.streams import DataStream
  File "/home/lduong/.local/lib/python2.7/site-packages/fuel/streams.py", line 3, in <module>
    import zmq
  File "/usr/lib/python2.7/dist-packages/zmq/__init__.py", line 62, in <module>
    from zmq.backend import *
  File "/usr/lib/python2.7/dist-packages/zmq/backend/__init__.py", line 22, in <module>
    _ns = select_backend('zmq.backend.cffi')
  File "/usr/lib/python2.7/dist-packages/zmq/backend/select.py", line 31, in select_backend
    mod = __import__(name, fromlist=public_api)
ImportError: No module named cffi

**Comment by longdt219** [comment]
It's also happening with sqrt example

**Comment by bartvm** [comment]
PyZMQ has a dependency on `cffi`: https://github.com/zeromq/pyzmq/blob/master/setup.py#L1258

Try reinstalling PyZMQ, because it should have been installed as part of its dependencies, but that obviously didn't happen. Probably a broken install, but nothing to do with Blocks in either case.

**Comment by dwf** [comment]
Yeah. `pip install pyzmq` has worked pretty flawlessly in the past for me, but it sounds like your zmq package may be installed by the operating system (as it's in `dist-packages`) and that may somehow be causing some problems... zeromq/pyzmq issue tracker or gitter chat may be of some help.

**Comment by longdt219** [comment]
Thanks @dwf and @bartvm , that's the conflict between my local and OS version. Resolved now.
