### ISSUE TITLE
ImportError: cannot import name PersistentCudaNdarrayID

### ISSUE THREAD

**Issue by astrung** [mila-udem/blocks-examples#54]
I use block version 0.1.1 and theano version 0.7.0
And when i try to run examples from blocks-examples i get this error:ImportError: cannot import name PersistentCudaNdarrayID.(https://github.com/mila-udem/blocks-examples : command : "python -m sqrt --num-batches 1000 sqrt/saved_state").How can i fix error?

**Comment by dwf** [comment]
As per mila-udem/blocks#904 see http://blocks.readthedocs.org/en/latest/setup.html
