### ISSUE TITLE
How to run machine_translation examples??

### ISSUE THREAD

**Issue by astrung** [mila-udem/blocks-examples#55]
How to run machine_translation examples??when i run by command:"python -m machine_translation  machine_translation/saved_state", i get this error:
import configurations - ImportError: No module named 'configurations'.
so how to run it with other commands or need some parameters???

**Comment by rizar** [comment]
@orhanf

**Comment by astrung** [comment]
Please add a README file for this example

**Comment by orhanf** [comment]
@astrung, i couldn't replicate the error that you got, is there a chance that you've changed the directory structure or renamed a file? But in order to pass some additional arguments you have two options: 
* add your additional argument(s) [here](https://github.com/mila-udem/blocks-examples/blob/master/machine_translation/__main__.py#L26-L32), to be parsed by the argument parser.
* or you can add them into the parameters dictionary in [configurations.py](https://github.com/mila-udem/blocks-examples/blob/master/machine_translation/configurations.py), and use them inside the [main](https://github.com/mila-udem/blocks-examples/blob/master/machine_translation/__init__.py#L31) function, they will be in the `config` dictionary.

**Comment by astrung** [comment]
I don`t have changed anythings.But can i forget some prepare_data or not??Can you give me how to run examples on your computer???(from begin-prepare data to end)??

**Comment by astrung** [comment]
I fixed module by add examples to PYTHONPATH-It seem main module can find configuration module.But i get an other error:FileNotFoundError: [Errno 2] No such file or directory: './data/vocab.cs-en.cs.pkl'>>Do i need prepare data??How to prepare data??

**Comment by astrung** [comment]
When i run : "python prepare_data.py">>Many errors which conflict between python 2 and python 3 appear(print , urlopen,....)>>do we have any versions for python 3?? 
I run block with python 3.4.3

**Comment by orhanf** [comment]
@astrung `prepare_data.py` is a convenience script and actually we have not spent any effort making it python3 compatible, so this is my bad, i'll fix incompatibility issues soon, thank you for the pointers.

For an immediate solution, i may suggest downloading the corresponding files and doing the pre-processing manually, by following `prepare_data.py` code.

**Comment by astrung** [comment]
I have installed python-2.7>>no error with this version>Run by command :"python2.7 prepare_data.py" + "python2.7 -m machine_translation" > No errors.
Another question:how long(your test with your computer) to run completed this example??
And can we save the model which trained by this example to a single file(a module for using to translate)??Does blocks support it???

**Comment by orhanf** [comment]
@astrung as far as i recall, it was taking 4-5 days (or approximately a week) for the model to converge by using all of the data available by wmt'15 on a titan black.

The model is automatically saved after every `t` iterations, and is controlled by the [`save_freq`](https://github.com/mila-udem/blocks-examples/blob/master/machine_translation/configurations.py#L106) parameter. 

Further, the [BleuValidator](https://github.com/mila-udem/blocks-examples/blob/master/machine_translation/sampling.py#L115) calculates bleu score on a given validation set after every `k` iterations, controlled by [`bleu_val_freq`](https://github.com/mila-udem/blocks-examples/blob/master/machine_translation/configurations.py#L115) and saves the best model so far. You can also track more than one model by changing [`track_n_models`](https://github.com/mila-udem/blocks-examples/blob/master/machine_translation/sampling.py#L130) parameter.

**Comment by astrung** [comment]
So we will save model to "search_model_cs2en" file after running?(In configuration.py)??Can I bring this file to another computer and use it??With using gcc, i think we will have conflicts with dynamic libraries(64bit-32bit) or python version.

**Comment by sjtufs** [comment]
@astrung Yes the parameters & iteration states & log will be saved there. According to my experience, to use it on another computer you have to make sure the data files (src_data, trg_data, dictionaries) are in the same directory as the computer that were used to train the model, because those information is written in model files and cannot be modified easily.

**Comment by astrung** [comment]
It creates model successfully.so how to see samples from model??I don`t see any samples from running.

**Comment by sjtufs** [comment]
@astrung You can figure this out by reading the code, it's all there.
'hook_samples' number of samples will be thrown out every 'sampling_freq' updates.

**Comment by astrung** [comment]
Can we check model is completed or not??From my log,I think training process has been terminated.Model is saved,but i haven`t seen any lines as "TRAINING HAS BEEN FINISHED".Re-runing command,my model is re-trained.

**Comment by orhanf** [comment]
@astrung what do you mean by "the model is completed or not" ? Do you mean [`config['finish_after']`](https://github.com/mila-udem/blocks-examples/blob/master/machine_translation/configurations.py#L100) many iterations are done and training has stopped ? Or is it terminated externally? 

Either way, if you re-run your model, with [`config['reload']=True`](https://github.com/mila-udem/blocks-examples/blob/master/machine_translation/configurations.py#L103), the model will re-load the parameters, state and log from the last checkpoint and will continue training.

**Comment by astrung** [comment]
Last lines from log(command will output to a file):
Training status:
	 batch_interrupt_received: False
	 epoch_interrupt_received: False
	 epoch_started: True
	 epochs_done: 1
	 iterations_done: 2228
	 received_first_batch: True
	 resumed_from: None
	 training_started: True
Log records from the iteration 2228:
	 decoder_cost_cost: 8

Then the model is saved.
With common examples,we wil get some lines as
 
:TRAINING HAS BEEN FINISHED:
-------------------------------------------------------------------------------
Training status:
     epochs_done: 1
     iterations_done: 235
So i think training can be stopped or terminated.

**Comment by orhanf** [comment]
and what is [`config['finish_after']`](https://github.com/mila-udem/blocks-examples/blob/master/machine_translation/configurations.py#L100) set to?

**Comment by astrung** [comment]
BUt why don`t  train with all of training data?

**Comment by orhanf** [comment]
Because this is just to show how to use NMT with search not to replicate an experimental result. `prepare_data.py` is just a convenience script but you can change it to download all the data and use it respectively.

**Comment by astrung** [comment]
When i try to run example with GPU,i get this error:
TypeError: ('Bad input argument to theano function with name "/home/admin/trungtv/python/lib/python2.7/site-packages/blocks/algorithms/__init__.py:253"  at index 0(0-based)', 'TensorType(float32, matrix) cannot store a value of dtype float64 without risking loss of precision. If you do not mind this loss, you can: 1) explicitly cast your data to float32, or 2) set "allow_input_downcast=True" when calling "function".'.
I have set floatX=float32 in .theanorc file.
It run normally with CPU.
How to fix it??

**Comment by orhanf** [comment]
Can you try explicitly adding `floatX=float32` into your `THEANO_FLAGS` and run

**Comment by astrung** [comment]
do we have any different between .theanorc file and THEANO_FLAGS?

**Comment by orhanf** [comment]
Please check [here](http://deeplearning.net/software/theano/library/config.html#environment-variables)

**Comment by astrung** [comment]
Run by THEANO_FLAGS still same error

**Comment by astrung** [comment]
First ,i train model with default parameter and CPU(model can be saved by float64bit) . Then i use with GPU and float32>>Can we have conflicts here??

**Comment by orhanf** [comment]
@astrung thank you for pointing this out, we've never tried switching between devices (cpu/gpu) during training.

So i've made the necessary changes [here](https://github.com/orhanf/blocks-examples/commit/ecfd228bdc40d1ae1b1c89f808a3916c7811f128), can you try it again with these changes.

**Comment by astrung** [comment]
How can we get BLEU score??BLEU class in sample.py,but in log or save files i don`t see any records for BLEU score(Only sample sentences-and sample sentences is so different with target sentences)

**Comment by astrung** [comment]
Will we get BLEU score after : iterations_done=5000??But model has been stopped after 2000 iterations_done

**Comment by sjtufs** [comment]
@astrung BLEU will be calculated after `config['val_burn_in'] = 80000` iterations, at the frequency of `config['bleu_val_freq'] = 5000`. With this configuration, the first BLEU score will come out at `85000`th iteration.

**Comment by astrung** [comment]
But why was my model stopped after 2000 iterations_done??

**Comment by sjtufs** [comment]
@astrung as @orhanf  mentioned previously, what is your  `config['finish_after']`?

**Comment by astrung** [comment]
I haven`t changed anything in code.

**Comment by orhanf** [comment]
What is the size (number of lines) of your training data, source and target? 

If it is stopping after ~2k updates, which is approximately 1 epoch, may be the data iterator is not able to send the right error to reset the iterator after the epoch. Can you try with the latest version of fuel please?

Also, it would be nice to see the last few outputs of the model (if the stderr and out are directed to different files, its better to see them both)

**Comment by astrung** [comment]
Now,i try to re-run,so i can not give last model output now ( It has been replaced ).But it takes so long.Do we have some differents for speed when use floatX=float32 or floatX=float64???(Last model with 2000 iterations takes 3 day)

**Comment by orhanf** [comment]
@astrung if you're running it on cpu, you should expect those numbers. But if you run it on a gpu, 2000 updates should take at most ~2 hours.

**Comment by astrung** [comment]
Last lines from stderr file:
INFO:machine_translation.checkpoint: Number of parameters loaded for computation graph: 37
INFO:machine_translation.checkpoint: Loading iteration state...
INFO:machine_translation.checkpoint: Loading log...
INFO:blocks.algorithms:Initializing the training algorithm
INFO:blocks.algorithms:The training algorithm is initialized
INFO:machine_translation.checkpoint: Saving model
INFO:machine_translation.checkpoint: ...saving parameters
INFO:machine_translation.checkpoint: ...saving iteration state
INFO:machine_translation.checkpoint: ...saving log
INFO:machine_translation.checkpoint: Model saved, took 37.0450139046 seconds.
INFO:machine_translation.checkpoint: Saving model
INFO:machine_translation.checkpoint: ...saving parameters
INFO:machine_translation.checkpoint: ...saving iteration state
INFO:machine_translation.checkpoint: ...saving log
INFO:machine_translation.checkpoint: Model saved, took 34.8084151745 seconds.
INFO:machine_translation.checkpoint: Saving model
INFO:machine_translation.checkpoint: ...saving parameters
INFO:machine_translation.checkpoint: ...saving iteration state
INFO:machine_translation.checkpoint: ...saving log
INFO:machine_translation.checkpoint: Model saved, took 37.9112868309 seconds.

LAST LINE FROM STDOUT:
Training status:
         batch_interrupt_received: False
         epoch_interrupt_received: False
         epoch_started: True
         epochs_done: 1
         iterations_done: 3609
         received_first_batch: True
         resumed_from: f1e281b4f0664784bbf92a5491c58d79
         training_started: True
Log records from the iteration 3609:
         decoder_cost_cost: 133.785651843

**Comment by astrung** [comment]
![untitled](https://cloud.githubusercontent.com/assets/9162294/11213013/3898012a-8d6c-11e5-8b9f-a559250169f0.png)
I think the speed problem depends on floatX.Did you run model with float32 or float64??

**Comment by orhanf** [comment]
So it has passed 2000 iterations and not stopped, that's good. 
You can further use `Timing(after_batch=True)` extension to monitor some timings at each iteration.

**Comment by astrung** [comment]
But it has stopped after last iteration.I don`t know why,but when i try to open stdout when running or run another examples.it may send a terminated signal to this process.I run by command:nohup python2.7 -m machine_translation > foo2.out 2> foo2.err < /dev/null &.>>>Do we have some interrupt  handles???

**Comment by astrung** [comment]
Error allocating 40000000 bytes of device memory (out of memory). Driver report 25915392 bytes free and 2146762752 bytes total >> I fix with smaller batch size=40 >> Error allocating 80000000 bytes.
How to fix it??

**Comment by orhanf** [comment]
Reduce batch size, number of hidden units and word embedding dimensions

**Comment by astrung** [comment]
Original exception:
        MemoryError: Error allocating 143360000 bytes of device memory (out of memory).
Apply node that caused the error: GpuAlloc{memset_0=True}(CudaNdarrayConstant{0.0}, Elemwise{add,no_inplace}.0, Shape_i{0}.0, Shape_i{1}.0)
Toposort index: 180
Inputs types: [CudaNdarrayType(float32, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar)]

Still conflicts between float32 and float64??Even i have deleted model??

**Comment by orhanf** [comment]
so this is a gpu memory problem, you have to shrink your model size, or run it on a larger gpu

**Comment by astrung** [comment]
config['enc_nhids'] = 800
    config['dec_nhids'] = 800

    config['enc_embed'] = 520
    config['dec_embed'] = 520

    config['batch_size'] = 40

I have reduced,but it need more memory(40000000<143360000)

**Comment by orhanf** [comment]
reduce it more :)

**Comment by astrung** [comment]
Half for all configs>Ok now and so fast:300 iterations in some minnutes:))

**Comment by astrung** [comment]
But will it reduce model's correct??

**Comment by orhanf** [comment]
Your model may not have enough capacity, resulting lower performance.

**Comment by astrung** [comment]
With default configuration parameters,how much for BLEU score???(from your model)

**Comment by orhanf** [comment]
Machine translation example implements [this](http://arxiv.org/pdf/1409.0473.pdf) paper, please see the paper for numbers.

**Comment by astrung** [comment]
After 85000 iterations:
INFO:machine_translation.checkpoint: Model saved, took 9.74095320702 seconds.
INFO:machine_translation.sampling:Started Validation:
INFO:machine_translation.sampling:Total cost of the validation: 0.0
ERROR: could not find reference file ./data/newstest2013.en.tok at ./data/multi-bleu.perl line 32.
INFO:machine_translation.sampling:
INFO:machine_translation.sampling:Validation Took: 0.00110449790955 minutes
ERROR:blocks.main_loop:Error occured during training.
Blocks will attempt to run `on_error` extensions, potentially saving data, before exiting and reraising the error.Note that the usual `after_training` extensions will *not* be run. The original error will be re-raised and also stored in the training log. Press CTRL + C to halt Blocks immediately.
Traceback (most recent call last):
  File "machine_translation/sampling.py", line 251, in _evaluate_model
    assert out_parse is not None
AssertionError:

Original exception:
        AssertionError
_________________________
OTHER ERROR!!!
In data folder, i have newstest2013.en.tok and newstest2013.cs.tok.But perl can not find file???

**Comment by astrung** [comment]
folder:
 -blocks-examples-master:
   +data
       -newstest2013.en.tok
       -newstest2013.cs.tok
       -multi-bleu.perl
   +machine_translation

And i run from blocks-examples-master

**Comment by orhanf** [comment]
Try giving full paths to all of your files in your `config`.

**Comment by astrung** [comment]
Add full path,still error:
ERROR: could not find reference file /home/admin/trungtv/blocks-examples-master/data/newstest2013.en.tok at /home/admin/trungtv/blocks-examples-master/data/multi-bleu.perl line 32
  File "machine_translation/sampling.py", line 251, in _evaluate_model
    assert out_parse is not None
AssertionError:

Original exception:
        AssertionError

**Comment by orhanf** [comment]
Total cost of the validation should not be 0.0 , probably there are no lines in you source file. Can you check newstest2013.en.tok and newstest2013.cs.tok files ?

**Comment by astrung** [comment]
That file is empty.When i use ls:
-rw-r--r--. 1 root root        0 Nov  6 18:52 newstest2013.cs.tok
-rw-r--r--. 1 root root        0 Nov  6 18:52 newstest2013.en.tok

**Comment by astrung** [comment]
Re-run prepare_data.py.Now files is not empty,but still error:
_________________________________________________
INFO:machine_translation.sampling:Started Validation:
ERROR:blocks.main_loop:Error occured during training.
  File "machine_translation/sampling.py", line 174, in do
    self._save_model(self._evaluate_model())
theano.compile.function_module.UnusedInputError: theano.function was asked to create a function computing outputs given certain inputs, but the provided input variable at index 3 is not part of the computational graph needed to compute the outputs: sequencegenerator_generate_outputs.
To make this error into a warning, you can pass the parameter on_unused_input='warn' to theano.function. To disable it completely, use on_unused_input='ignore'.

Original exception:
        UnusedInputError: theano.function was asked to create a function computing outputs given certain inputs, but the provided input variable at index 3 is not part of the computational graph needed to compute the outputs: sequencegenerator_generate_outputs.
To make this error into a warning, you can pass the parameter on_unused_input='warn' to theano.function. To disable it completely, use on_unused_input='ignore'.
Use of uninitialized value $length_reference in numeric eq (==) at /home/admin/trungtv/blocks-examples-master/data/multi-bleu.perl line 136.

**Comment by orhanf** [comment]
Add on_unused_input='warn' on your `THEANO_FLAGS`, as it is written in the error text. 

@astrung please read the errors carefully and double check [blocks-users group](https://groups.google.com/forum/#!forum/blocks-users) and other issues in this repo, for example this one is mentioned [here](https://github.com/mila-udem/blocks-examples/issues/58) before.

**Comment by astrung** [comment]
Is validation_out.txt translated from newstest2013.cs.tok and compared with newstest2013.en.tok??
But model output and target is very different,and with low BLEUSCORE ( BLEU= [8 ;10] )- do we need more word-embedding dimensions ??? ( In some papers, they report that standart embedding-dimensions is 640)

**Comment by orhanf** [comment]
I guess this is a research question rather an issue about the code base. 
@rizar i think we can close this issue, thanks
