### ISSUE TITLE
Machine translation blocks.main_loop error

### ISSUE THREAD

**Issue by kienwei** [mila-udem/blocks-examples#58]
ran the machine translation and got this error at validation:

INFO:machine_translation.sampling:Started Validation: 
ERROR:blocks.main_loop:Error occured during training.

Blocks will attempt to run `on_error` extensions, potentially saving data, before exiting and reraising the error. Note that the usual `after_training` extensions will *not* be run. The original error will be re-raised and also stored in the training log. Press CTRL + C to halt Blocks immediately.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
...
...
...
Original exception:
	UnusedInputError: theano.function was asked to create a function computing outputs given certain inputs, but the provided input variable at index 3 is not part of the computational graph needed to compute the outputs: sequencegenerator_generate_outputs.
To make this error into a warning, you can pass the parameter on_unused_input='warn' to theano.function. To disable it completely, use on_unused_input='ignore'.
Use of uninitialized value $length_reference in numeric eq (==) at ./data/multi-bleu.perl line 148.

blocks 0.1.1
fuel 0.1.1
bleeding edge Theano 0.7.0

**Comment by orhanf** [comment]
Can you please add `on_unused_input='warn'` to your `THEANO_FLAGS` and try again.

**Comment by fstahlberg** [comment]
orhanf thanks on_unused_input='warn' solved it for me

**Comment by orhanf** [comment]
@rizar this issue can be closed, thanks.

**Comment by Beronx86** [comment]
@rizar  Is it reliable to use the flat ` on_unused_input='warn'` on this occasion?
