### ISSUE TITLE
Using attention networks when each utterance is a sequence of vectors without a lookup table.

### ISSUE THREAD

**Issue by 7404N** [mila-udem/blocks-examples#59]
I am not sure how to modify the example for either of the reverse_words or machine_translation examples to be able to use it with a dataset to do say speech synthesis. 

There is no lookup table for each phoneme/character and each utterance maybe of dimension [num of frames x feature dimension]. So say utt1 is say dimension 700  x 50, utt2 is 600 x 50 etc.  At each time I would like the encoder to see the entire utterance sequence without using a  lookup table .

Is there a simple pointer on how to train an attention network with this kind of input?

I am stuck with mainly the following:
1. How to load this kind of data into a file using fuel, since all the examples I have seen so far are converting it to one stream where it iterates over rows, when I need it to iterate over matrices with variable number of rows.

2. If I do use the stream how to make the attention network know the end of utterance without using a lookup table or  an eos tag. Instead of a row vector can I give a matrix as input to it?

Any pointers would be helpful.

**Comment by dwf** [comment]
The issue tracker is for problems encountered with the code as it exists today. This is a research question, about (as far as I know) an open research question, and pretty clearly out of scope.
