### ISSUE TITLE
Best_bleu_model npz file can not be restored

### ISSUE THREAD

**Issue by wenhuchen** [mila-udem/blocks-examples#72]
Hello,

I found out that the best_bleu_model....npz file is much larger than params.npz. It's storing different parameters than params.npz, how can I restore it? 
Hope to get your help.

**Comment by orhanf** [comment]
You can try [this](https://github.com/orhanf/blocks-examples/commit/a103c8a78647e1e40251fe69dc8ea670e90780f1) fix, it should solve the issue

**Comment by wenhuchen** [comment]
Thanks, it works
