### ISSUE TITLE
A wried bug in the machine translation example, when the number of decoder hidden units blew 25.

### ISSUE THREAD

**Issue by Beronx86** [mila-udem/blocks-examples#80]
I think the bug is easy to reproduce, just modify line11 in machine_translation/configuration.py to
<code>config['dec_nhids'] = 25</code>
The error message is:
<pre><code>
ValueError: total size of new array must be unchanged
Apply node that caused the error: Reshape{4}(Elemwise{add,no_inplace}.0, MakeVector{dtype='int64'}.0)
Toposort index: 983
Inputs types: [TensorType(float64, 3D), TensorType(int64, vector)]
Inputs shapes: [(10, 80, 25), (4,)]
Inputs strides: [(16000, 200, 8), (8,)]
Inputs values: ['not shown', array([10, 80, 12,  2])]
Outputs clients: [[Reduce{maximum}{3}(Reshape{4}.0), Elemwise{Composite{(EQ(i0, i1) * i2)}}(InplaceDimShuffle{0,1,2,x}.0, Reshape{4}.0, InplaceDimShuffle{0,1,2,x}.0)]]
</pre></code>

**Comment by Beronx86** [comment]
I tested it. <code>dec_nhids</code> larger than <code>25</code> is OK.
I cannot figure out in which <code>Reshape</code> operation the error occurs. `LookupFeedbackWMT15.feedback ` method and `SequenceContentAttention.compute_energies` method contain `reshape` operation. But the shape does not match.

**Comment by rizar** [comment]
This is very strange, especially if it really crashes only when `dec_nhids` is below certain value. You can try using Theano test values for faster debugging.

**Comment by ohadzad** [comment]
Is it possible that you try to resume training a model which has been trained with different set of parameters? If it is, than it probably has problems with changing the network structure of an existing model.

**Comment by Beronx86** [comment]
@ohadzad Hi, you may test it on your machine. I think it is not caused by reloading parameters of diferent configuration.

**Comment by Beronx86** [comment]
The following code may be used for reproduce the bug. Just keep `state_dim <= 25`.

```python
import numpy
import theano

from blocks.initialization import Constant
from blocks.initialization import IsotropicGaussian
from theano import tensor

from video_caption.decoder import Decoder

rng = numpy.random.RandomState(1234)


def test_decoder():
    source_steps = 20
    target_steps = 30
    batch_size = 9

    vocab_size = 300
    embedding_dim = 30
    state_dim = 25
    represent_dim = 100

    inits = {
        'weights_init': IsotropicGaussian(0.1),
        'biases_init': Constant(0.)
    }

    decoder = Decoder(vocab_size, embedding_dim,
                      state_dim, represent_dim, **inits)
    decoder.initialize()

    representation = tensor.tensor3('representation')
    source_mask = tensor.matrix('source_mask')
    target_sentence = tensor.lmatrix('target_sentence')
    target_mask = tensor.matrix('target_mask')
    cost = decoder.cost(representation, source_mask,
                        target_sentence, target_mask)

    f = theano.function(
        inputs=[representation, source_mask,
                target_sentence, target_mask],
        outputs=cost)

    rep_val = rng.uniform(
        size=(source_steps, batch_size, represent_dim),
        low=0., high=1.)
    targ_val = rng.randint(
        size=(batch_size, target_steps),
        low=0, high=vocab_size)
    sour_mask_val = numpy.ones((source_steps, batch_size))
    targ_mask_val = numpy.ones((batch_size, target_steps))

    cost_val = f(rep_val, sour_mask_val, targ_val, targ_mask_val)

if __name__ == '__main__':
    test_decoder()

```

**Comment by rizar** [comment]
Many thanks for trying to provide a minimal non-working example! Unfortunately, `video_caption` module is necessary to run it. 
```
from video_caption.decoder import Decoder
```

**Comment by Beronx86** [comment]
Hi @rizar, I am sorry for that. I just copied the machine_translation decoder to my own project. Now I modified the code. You may copy the file to the `blocks-examples` folder and test it. 
On my computer, the following error occurred. It seems that the error occurred when the `state_dim` is odd.
```
ValueError: GpuReshape: cannot reshape input of shape (30, 9, 25) to shape (30, 9, 12, 2).
Apply node that caused the error: GpuReshape{4}(GpuElemwise{add,no_inplace}.0, MakeVector{dtype='int64'}.0)
Toposort index: 329
Inputs types: [CudaNdarrayType(float32, 3D), TensorType(int64, vector)]
Inputs shapes: [(30, 9, 25), (4,)]
Inputs strides: [(225, 25, 1), (8,)]
Inputs values: ['not shown', array([30,  9, 12,  2])]
Outputs clients: [[HostFromGpu(GpuReshape{4}.0)]]
```

**Comment by orhanf** [comment]
@Beronx86, from the shapes, especially `(30, 9, 12, 2)`, i suspect that this is caused by `Maxout` layer in the `Readout`. We have hard coded `num_pieces=2` [here](https://github.com/mila-udem/blocks-examples/blob/master/machine_translation/model.py#L177-L178) and it raises when `state_dim` is odd. 
So either set `state_dim` to an even number, or play with `num_pieces` to get a division without a remainder. Or simply change `Maxout` layer into a `Tanh` layer if you don't want to play with those.

Sorry for my late response, i'll try to close some issues this week.

**Comment by Beronx86** [comment]
Hi @orhanf , thanks for your reply. Your response makes sense.
