### ISSUE TITLE
How to do machine translation

### ISSUE THREAD

**Issue by jestinjoy** [mila-udem/blocks-examples#83]
I am looking for an example that does machine translation. I have run the training for one day with the following result

```
Training status:
         batch_interrupt_received: False
         epoch_interrupt_received: False
         epoch_started: True
         epochs_done: 0
         iterations_done: 11
         received_first_batch: True
         resumed_from: None
         training_started: True
Log records from the iteration 11:
         decoder_cost_cost: 350.873748779
```
 Epochs done is still showing 0.

Anyway got the model saved in _search_model_cs2en_ . Looking for how to do translation based on this.

**Comment by orhanf** [comment]
Please check #43 , translation by using a trained model.
But i suspect you are running this on CPU since the number of iterations done is only `11`, after a day of training on a decent GPU, you should observe something around `70k` iterations.

**Comment by Beronx86** [comment]
HI @orhanf , can I reproduce the result with the default configuration?
