### ISSUE TITLE
Cannot get the almost diagonal align map in the machine trainslation example

### ISSUE THREAD

**Issue by Beronx86** [mila-udem/blocks-examples#92]
[sample0_heatmap.pdf](https://github.com/mila-udem/blocks-examples/files/189570/sample0_heatmap.pdf)
[sample1_heatmap.pdf](https://github.com/mila-udem/blocks-examples/files/189568/sample1_heatmap.pdf)
HI, 
I draw the align heatmap during training. The heatmap is took from training iteration 18000. I cannot get an align map close to the result in the paper.

**Comment by Beronx86** [comment]
[sample0_heatmap.pdf](https://github.com/mila-udem/blocks-examples/files/191752/sample0_heatmap.pdf)
[sample1_heatmap.pdf](https://github.com/mila-udem/blocks-examples/files/191753/sample1_heatmap.pdf)
I can get the almost diagonal align map now. The training iterations of the previous map is not enough. Note that the y axis in the map is not right.

**Comment by rizar** [comment]
Since you report that it works, I am closing the issue.
